#test get Goals
# GET http://localhost:5000/api/goals/

#test add Goals
# POST http://localhost:5000/api/goals/ HTTP/1.1
# content-type: application/json

# {
#     "text":"asfsdfghdfh"
# }

#test delete Goals
# DELETE  http://localhost:5000/api/goals/6278e861f3b68ef00573d569

# PUT  http://localhost:8000/api/goals/627646284b3659bfe0957cb5 HTTP/1.1
# content-type: application/json

# {
#     "text":"omar muhammed"
# }



POST http://localhost:8000/api/user/ HTTP/1.1
content-type: application/json

 {
     "name":"omar",
    "email":"mod199523@gmail.com",
     "password":"0595288061",
 }

# POST http://localhost:8000/api/user/login HTTP/1.1
# content-type: application/json

# {
#     "email":"model199523@gmail.com",
#     "password":"0595288061",
# }
 
# GET http://localhost:5000/api/member/me

# GET http://localhost:5000/api/financial/

